"""Generate the deployable HTML. Run: python tools/build.py. No build needed to serve."""
from pathlib import Path
from html import escape
from skills_data import render_skills

ROOT = Path(__file__).resolve().parent.parent
PROJECTS = [
    dict(slug='tedx', name='TEDxThirdWard', category='Web platforms', label='A stage for ideas. A workspace for the team.', stack='React / TypeScript / PostgreSQL', image='tedx', color='red',
         intro='A public website and a custom admin console for a local TEDx organization. Speakers, events, and stories on the outside; practical content tools for the team behind them.',
         problem='The public site needed to tell the story of the events. Behind the scenes, non-technical team members needed a way to update that content without editing code.',
         built='I built the public portal in React and TypeScript, with a separate admin console for managing content. Serverless Node.js functions handle authentication and database operations against PostgreSQL. The application is deployed on Vercel.',
         detail='Authentication uses JWTs and bcrypt password hashing, with forced password rotation for new users. Building the admin interface meant turning relationships between speakers, events, and posts into controls that the team could use.',
         lesson='This project brought stakeholder conversations directly into implementation: volunteer management and admin access requirements shaped both the interface and the backend. The source belongs to TEDxThirdWard and is not public.',
         links=[('Visit website','https://www.tedxthirdward.com/')]),
    dict(slug='nutriscan', name='NutriScan AI', category='AI experiments', label='From a 36-hour sprint to two awards.', stack='React / Gemini / DigitalOcean', image='nutriscan', color='green',
         intro='A student-focused nutrition prototype, co-built at HackWestern 12. It explores photo-based AI input and budget-friendly meal planning in one web app.',
         problem='The team set out to make nutrition guidance easier for students to explore, with meal suggestions that account for a limited budget. The time constraint: build and present the idea in 36 hours.',
         built='I co-developed the React and TypeScript interface and helped integrate multimodal AI into the experience. The project uses Google Gemini 2.5 Flash and DigitalOcean Gradient AI, with Tailwind CSS for the interface.',
         detail='The prototype takes photo input and generates personalized meal suggestions. It is a hackathon exploration, not a validated diagnostic tool; the useful engineering challenge was connecting image input, model responses, and a readable result.',
         lesson='NutriScan won the Sun Life Best Health Hack and Best Use of DigitalOcean AI awards at HackWestern 12. The sprint pushed the team to coordinate interface work and AI integration around a working demo.',
         links=[('Source code','https://github.com/ZElnagar/HackWestern12'),('Open demo','https://zelnagar.github.io/HackWestern12/')]),
    dict(slug='playlist', name='Adaptive Playlist Generator', category='Web platforms', label='A playlist that starts with a mood.', stack='Python / Flask / Spotify API', image='playlist', color='purple',
         intro='A Flask app for creating Spotify playlists around mood and context, with genre search and a swipe-style selection interface.',
         problem='A genre alone does not describe what someone wants to listen to. This project explores a more interactive way to choose music using both context and individual song selections.',
         built='I built a Python and Flask backend around the Spotify Web API, paired with an HTML, CSS, and JavaScript frontend. Users can search genres and select music through a Tinder-style interface to assemble a custom playlist.',
         detail='The backend is the boundary between the browser and the third-party API. Keeping endpoints clear and focused was central to making the playlist flow understandable and maintainable.',
         lesson='Working with a third-party API made planning the request flow as important as building the interface. It also reinforced the value of mapping out the experience before writing the endpoints.',
         links=[('Source code','https://github.com/tristanbeley92/PlaylistGenerator')]),
    dict(slug='unity', name='Escape PolyLand', category='Games', label='Small polygons. One very big boss fight.', stack='C# / Unity / Cinemachine', image='unity', color='orange',
         intro='A team-built, low-poly 3D RPG with enemy AI, puzzles, multiple levels, and a final boss encounter.',
         problem='The team needed to bring combat, puzzles, and progression together into a playable game. Each system had to work on its own and still fit into the same world.',
         built='Working with a group of four, I helped create the game in Unity using C#, Cinemachine, and Blender assets. The game features custom enemy behavior and a progression system that leads through multiple levels to the boss fight.',
         detail='Enemy behavior, puzzle logic, and level progression each introduce their own state. Breaking large features into smaller systems helped the team reason about those interactions and test changes.',
         lesson='Shared game development made version control and communication essential. Keeping work divided into manageable systems helped us coordinate changes without losing sight of the complete game.',
         links=[('Source code','https://github.com/AlexandraLHeureuxECE/final-project-thefellowship')]),
    dict(slug='opencam', name='Open Cam Lab', category='AI experiments', label='Computer vision, right in the browser.', stack='React / face-api.js / AWS Amplify', image='opencam', color='blue',
         intro='A browser-based facial analysis experiment with real-time face detection, multiple bounding boxes, emotion labels, and image uploads.',
         problem='Real-time visual feedback needs to stay responsive while a model processes camera frames. The project explores how to connect that processing with a usable frontend.',
         built='I built the application with React, TypeScript, face-api.js, and Redux Toolkit. It supports both live detection and uploaded images, and was deployed on AWS Amplify.',
         detail='The interface draws bounding boxes for multiple faces and updates predicted labels as the input changes. Those labels are model outputs rather than facts about a person. Redux Toolkit provides a shared place to manage application state.',
         lesson='This project made frontend performance tangible: model processing and UI updates share the browser. It also gave me practical experience with state management and deploying a React application to AWS.',
         links=[('Source code','https://github.com/tristanbeley92/open-cam-lab'),('Open demo','https://main.df4g3v16sxvtp.amplifyapp.com/')]),
    dict(slug='portfolio', name='This little corner of the web', category='Web platforms', label='The first project. Still evolving.', stack='HTML / CSS / JavaScript', image='portfolio', color='yellow',
         intro='My portfolio started as my first project: a site built with HTML, CSS, and JavaScript. It has become a place to document the work that came after it.',
         problem='A portfolio needs to do more than list technologies. Visitors should be able to understand what a project does, what I worked on, and what I learned from building it.',
         built='The current version uses standalone HTML pages, a shared stylesheet, and a small JavaScript file. Project write-ups and page templates are maintained in a Python build script that generates the static files.',
         detail='Content is available without JavaScript. Project filters, preview switching, and the command menu are progressive enhancements. Images are compressed WebP files, and motion respects the reduced-motion preference.',
         lesson='The original version taught me the fundamentals of building from scratch. This iteration keeps that lightweight foundation while giving the projects enough space to tell their own stories.',
         links=[('Source code','https://github.com/tristanbeley92/Portfolio_Beley')]),
]

def tags(text):
    return '<div class="tags">'+''.join(f'<span>{escape(t.strip())}</span>' for t in text.split('/'))+'</div>'

def art(p):
    if p['slug']=='tedx':
        return '<div class="tedx-art"><span>IDEAS WORTH SPREADING</span><strong>TED<span>x</span></strong><b>ThirdWard</b><small>Independent ideas. Shared possibilities.</small></div>'
    if p['slug']=='nutriscan':
        return '<div class="nutrition-art"><span class="mini-label">NUTRISCAN / HACKWESTERN 12</span><div class="scan-orbit">✳</div><strong>A little insight.<br>A healthier plate.</strong><span class="scan-label">PHOTO → INSIGHT → MEAL PLAN</span></div>'
    if p['slug']=='playlist':
        return '<div class="record-art"><div class="record"><span>tb<br>33⅓</span></div><span class="record-label">GOOD CODE.<br>BETTER PLAYLISTS.</span></div>'
    return f'<img src="assets/{p["image"]}.webp" alt="{escape(p["name"])} project preview" width="1000" height="650" loading="lazy" decoding="async">'

def card(p,i):
    return f'''<article class="project-card" data-category="{p['category']}"><a class="project-art {p['color']}" href="project-{p['slug']}.html" aria-label="Read about {escape(p['name'])}">{art(p)}<span class="art-arrow" aria-hidden="true">↗</span></a><div class="project-meta"><span class="mono">0{i+1} / {p['category']}</span><h3><a href="project-{p['slug']}.html">{p['name']}</a></h3><p>{p['label']}</p>{tags(p['stack'])}</div></article>'''

def header(active):
    nav=''.join(f'<a href="{slug}.html" '+('aria-current="page"' if active==slug else '')+f'>{name}</a>' for slug,name in [('about','About'),('experience','Experience'),('skills','Skills'),('projects','Projects')])
    return f'''<a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="index.html" aria-label="Tristan Beley home">tb<span>↗</span></a><nav aria-label="Main navigation">{nav}<a href="#contact">Contact <span aria-hidden="true">↗</span></a></nav><button class="command-trigger" data-command aria-label="Open page search"><span>⌘</span> K</button><button class="menu-toggle" aria-expanded="false" aria-controls="mobile-menu">Menu +</button></header><nav id="mobile-menu" aria-label="Mobile navigation" hidden>{nav}<a href="#contact">Contact ↗</a></nav>'''

def footer():
    return '''<section id="contact" class="contact"><div><span class="eyebrow">NEXT CONVERSATION</span><h2>Got something<br>in mind<span>?</span></h2><p>A project, an opportunity, or a good hockey debate.<br>My inbox is a good place to start.</p></div><div class="contact-actions"><a class="button dark" href="mailto:tristanbeley@gmail.com">Say hello <span>↗</span></a><button class="text-button" data-copy>Copy email address <span>⧉</span></button><span class="copy-status" role="status"></span></div></section><footer><a class="brand" href="index.html">tb<span>↗</span></a><span>© 2026 Tristan Beley</span><div><a href="https://github.com/tristanbeley92">GitHub ↗</a><a href="https://www.linkedin.com/in/tristan-beley-112652293/">LinkedIn ↗</a><a href="Images/WorthTheCall_TristanBeley_Resume.pdf">Résumé ↗</a></div><a href="#top">Back to top ↑</a></footer><dialog id="command-dialog" aria-labelledby="command-title"><div class="dialog-top"><h2 id="command-title">Where to?</h2><button data-close aria-label="Close page search">Esc ×</button></div><input id="command-search" type="search" placeholder="Find a page or project…" aria-label="Search pages and projects"><div class="command-results"></div><p class="mono">A little shortcut to the good stuff.</p></dialog>'''

def page(slug,title,description,body):
    html=f'''<!doctype html><html lang="en" id="top"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="{escape(description,quote=True)}"><meta name="theme-color" content="#f6f5f1"><title>{title} | Tristan Beley</title><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="style.css"><script src="script.js" defer></script><noscript><style>.skills-explorer,.command-trigger,.menu-toggle,.filters,.stage-tabs,[data-copy]{{display:none!important}}@media(max-width:700px){{#mobile-menu[hidden]{{display:grid!important}}}}</style></noscript></head><body>{header('projects' if slug.startswith('project-') else slug)}<main id="main">{body}</main>{footer()}</body></html>'''
    (ROOT/f'{slug}.html').write_text(html,encoding='utf-8')

def intro(number,kicker,title,desc):
    return f'<section class="page-intro"><span class="eyebrow">{number} / {kicker}</span><h1>{title}</h1><p>{desc}</p></section>'

home='''<section class="hero"><div class="hero-copy"><p class="hero-hello">Hey, I’m Tristan.</p><h1>Curious mind.<br>Hands-on builder.<br><span class="blue-text">Tristan Beley.</span></h1><p>I’m a Junior Software Engineer at ConvergentIS and a Software Engineering student at Western. I work on production services, cloud infrastructure, and the tools that help other developers ship.</p><div class="hero-actions"><a class="button dark" href="projects.html">Explore my work <span>↗</span></a><a class="text-link" href="about.html">A little about me <span>→</span></a></div><div class="hero-foot mono"><span>DEVELOPER. CO-FOUNDER. HOCKEY PLAYER.</span><span>SCROLL TO EXPLORE ↓</span></div></div><div class="workspace"><div class="workspace-grid"></div><span class="workspace-note mono">a few things in my orbit</span><div class="code-window"><div class="window-bar"><span>● ● ●</span><span>tristan.ts</span><span>↗</span></div><div class="code"><span class="code-muted">// always a work in progress</span><br><span class="code-purple">const</span> tristan = {<br>&nbsp; studying: <span class="code-green">"Software Engineering"</span>,<br>&nbsp; building: <span class="code-green">"RoleColorFinder"</span>,<br>&nbsp; offscreen: <span class="code-green">"At the rink"</span>,<br>&nbsp; curiosity: <span class="code-orange">Infinity</span><br>};<br><br><span class="code-purple">export default</span> tristan<span class="cursor">▌</span></div><div class="window-bottom"><span class="status-dot"></span> ideas → code → something useful</div></div><div class="portrait-sticker"><img src="assets/portrait.webp" alt="Tristan Beley" width="180" height="180" fetchpriority="high"><span>hey, I'm Tristan ✌</span></div><div class="award-sticker"><span>✳</span><div>HackWestern 12<br><b>2× award winner</b></div></div><span class="floating-star" aria-hidden="true">✳</span><span class="workspace-caption mono"></span></div></section><div class="ticker" aria-label="Areas of work"><span>WEB DEVELOPMENT</span><i>✳</i><span>PRODUCT THINKING</span><i>✳</i><span>AI EXPERIMENTS</span><i>✳</i><span>GAME DEVELOPMENT</span><i>✳</i></div><section class="section"><div class="section-heading"><div><span class="eyebrow">01 / SELECTED WORK</span><h2>Less talk. More builds<span class="blue-text">.</span></h2></div><a class="text-link" href="projects.html">All projects ↗</a></div><div class="project-grid">'''+''.join(card(p,i) for i,p in enumerate(PROJECTS[:2]))+'''</div></section><section class="about-strip"><div><span class="eyebrow">Away from the keyboard</span><h2>Not always<br>behind a screen.</h2></div><div><p>Alongside ConvergentIS, I co-founded RoleColorFinder. Outside of work and school, I’m usually playing hockey, rebuilding a classic car, or working on a Lego set.</p><a class="text-link" href="about.html">Meet the rest of me ↗</a></div><span class="big-asterisk" aria-hidden="true">✳</span></section>'''
page('index','Software, curiosity & a little play','Tristan Beley: Software Engineering student at Western, co-founder, and builder of web applications, AI experiments, and games.',home)

about=intro('01','ABOUT','A developer.<br>A teammate.<br><em>A work in progress.</em>','I’m Tristan, a Software Engineering student at Western University. Code is one part of the story.')+'''<section class="about-layout section"><figure class="hockey-photo"><img src="assets/hockey.webp" alt="Tristan on the hockey rink" width="800" height="900" loading="lazy"><figcaption class="mono">OFFLINE MODE / AT THE RINK</figcaption></figure><div class="prose"><span class="eyebrow">A LITTLE CONTEXT</span><h2>I like work that<br>becomes something.</h2><p>That might be a website a team can update themselves, a playlist someone actually wants to listen to, or a game with a boss worth beating. My projects have taken me through frontend interfaces, Python backends, browser-based AI, and Unity.</p><p>I’m also Co-Founder and CTO at RoleColorFinder. My work there spans technical direction, architecture, and conversations with early users about what the product should become.</p><h3>Before the code</h3><p>As an Assistant Project Manager at Konstruct21, I worked with timelines, budgets, teams, and vendors. That experience gave me a practical appreciation for scope and communication: a plan only helps if people can execute it together.</p><h3>Same teammate, different arena</h3><p>I’ve played competitive hockey throughout my life. It’s a different kind of problem-solving, but the discipline, resilience, and reliance on teammates carry into how I approach technical work.</p><a class="text-link" href="experience.html">Where I’ve put that to work ↗</a></div></section><section class="section fact-grid"><article><span class="eyebrow">LEARNING</span><h3>Western University</h3><p>Software Engineering</p><p>Western Developers Society · Frontend Team<br>Western Investment Club · Researcher</p></article><article><span class="eyebrow">BUILDING TOGETHER</span><h3>HackWestern 12</h3><p>NutriScan AI · built in 36 hours</p><p>Sun Life Best Health Hack<br>Best Use of DigitalOcean AI</p><a class="text-link" href="project-nutriscan.html">Read about the build ↗</a></article></section>'''
page('about','About','Meet Tristan Beley: Western Software Engineering student, RoleColorFinder co-founder, and competitive hockey player.',about)

roles=[('Sept 2025 to Present','Co-Founder + CTO','RoleColorFinder','01','A color-matching platform, built from the early product stage.',['Own technical strategy and architecture decisions as the platform develops toward a broader release.','Work with early users and stakeholders to decide what to build and how to prioritize it.','Balance hands-on development with product positioning and the operational responsibilities of co-founding a company.'],'Architecture / Product strategy / Leadership'),('Oct 2025 to Jan 2026','Game Consultant','Layyal Tech','02','Design and technical guidance for an independent studio project.',['Advised on game design decisions and whether proposed features were technically feasible.','Reviewed implementation approaches and discussed engineering tradeoffs with the development team.'],'Game design / Technical consulting'),('Apr 2024 to Aug 2025','Assistant Project Manager','Konstruct21','03','Project delivery in the construction industry.',['Managed project timelines, budgets, and communication with stakeholders.','Coordinated teams and vendors to keep active projects within scope and on schedule.','Developed planning and execution habits that now inform how I approach software projects.'],'Planning / Coordination / Stakeholder communication')]
roles = [
    ('Aug 2026 to Present', 'Junior Software Engineer', 'ConvergentIS', '01',
     'Application code, infrastructure, and release ownership across shared platform services.', [
      'Build production fixes and reliability improvements across 10+ TypeScript and Node.js microservices and Temporal workers.',
      'Build developer tooling, including a diff-driven cross-environment migration engine and repeatable workflows spanning nine Kubernetes clusters.',
      'Own releases across four environments, coordinate team readiness, run CI/CD and GitOps deployments, and serve as the primary responder for production incidents.'
     ], 'TypeScript / Node.js / AWS / Kubernetes / Docker / Temporal / RIO'),
    ('May 2026 to Aug 2026', 'Cloud/Software Engineer Intern', 'ConvergentIS', '02',
     'Took on deployment, migration, testing, and debugging responsibilities after a senior engineer left the team.', [
      'Owned deployments, migrations, automated testing, monitoring, and production debugging while learning the platform’s existing systems.',
      'Led a sandbox AWS EKS environment promotion to pre-production and CI/CD across 10+ microservices, resolving 15+ reliability and security gaps.',
      'Built AI-assisted cloud security automation with Claude Code and MCP across multiple AWS accounts. Reviewed and validated changes to improve SOC 2 preparedness from roughly 56% toward a 95%+ goal.'
     ], 'TypeScript / AWS / EKS / Kubernetes / Temporal / Claude Code / MCP'),
] + [(date, title, company, f'{i+3:02}', summary, bullets, stack)
     for i, (date, title, company, number, summary, bullets, stack) in enumerate(roles)]
experience=intro('02','EXPERIENCE','Different roles.<br><em>Shared ownership.</em>','My work spans production engineering at ConvergentIS, co-founding RoleColorFinder, and earlier roles in consulting and project management.')+'<section class="timeline section">'+''.join(f'<article class="role"><div class="role-date mono"><span>{n}</span>{date}</div><div><span class="eyebrow">{company}</span><h2>{title}</h2><p class="role-summary">{summary}</p><ul>'+''.join(f'<li>{b}</li>' for b in bullets)+f'</ul>{tags(stack)}</div></article>' for date,title,company,n,summary,bullets,stack in roles)+'</section><aside class="resume-banner"><div><span class="eyebrow">THE TAKEAWAY VERSION</span><h3>All the essentials, in a PDF.</h3></div><a class="button dark" href="Images/WorthTheCall_TristanBeley_Resume.pdf">Open résumé ↗</a></aside>'
page('experience','Experience','Experience at ConvergentIS, RoleColorFinder, Layyal Tech, and Konstruct21: technical leadership, game consulting, and project management.',experience)

skills=intro('03','SKILLS','My everyday<br><em>tools.</em>','The languages, cloud services, and tools I use across work and personal projects.') + render_skills()

page('skills','Skills','The tools behind Tristan’s projects, with practical examples across frontend, backend, AI, games, and cloud.',skills)

projects=intro('04','PROJECTS','Built out of<br><em>“what if?”</em>','Client work, hackathon sprints, and experiments that became working projects. Open one for the details.')+'''<section class="project-stage" aria-label="Featured project preview"><div class="stage-info"><span class="eyebrow">ON THE WORKBENCH</span><h2 id="stage-title">TEDxThirdWard</h2><p id="stage-description">A public website and a custom admin console for the people behind the event.</p><a id="stage-link" class="button dark" href="project-tedx.html">Explore the build ↗</a><div class="stage-tabs" role="group" aria-label="Choose featured project"><button data-preview="tedx" aria-pressed="true">01 <span>TEDx</span></button><button data-preview="nutriscan" aria-pressed="false">02 <span>NutriScan</span></button><button data-preview="playlist" aria-pressed="false">03 <span>Playlist</span></button></div></div><div class="stage-art project-art red" id="stage-art">'''+art(PROJECTS[0])+'''</div></section><section class="section"><div class="project-toolbar"><h2>The project shelf<span class="blue-text">.</span></h2><div class="filters" role="group" aria-label="Filter projects"><button data-filter="All" aria-pressed="true">All <span>06</span></button><button data-filter="Web platforms" aria-pressed="false">Web</button><button data-filter="AI experiments" aria-pressed="false">AI</button><button data-filter="Games" aria-pressed="false">Games</button></div></div><p class="sr-only" id="filter-status" role="status">6 projects</p><div class="project-grid">'''+''.join(card(p,i) for i,p in enumerate(PROJECTS))+'''</div></section>'''
page('projects','Projects','Explore six projects: TEDxThirdWard, NutriScan AI, a Spotify playlist generator, Escape PolyLand, Open Cam Lab, and this portfolio.',projects)

for i,p in enumerate(PROJECTS):
    body=f'<section class="case-intro"><a class="text-link" href="projects.html">← Back to the project shelf</a><div class="eyebrow">{p["category"]} / BUILD NOTES</div><h1>{p["name"]}</h1><p>{p["intro"]}</p>{tags(p["stack"])}<div class="case-links">'+''.join(f'<a class="button dark" href="{url}">{label} ↗</a>' for label,url in p['links'])+f'</div></section><div class="case-art project-art {p["color"]}">{art(p)}</div><section class="case-body section"><aside><span class="eyebrow">INSIDE THE BUILD</span><a href="#problem">01 The starting point</a><a href="#built">02 What I built</a><a href="#detail">03 Under the hood</a><a href="#lesson">04 What stayed with me</a></aside><div class="prose">'+''.join(f'<section id="{key}"><span class="eyebrow">0{n}</span><h2>{heading}</h2><p>{p[key]}</p></section>' for n,key,heading in [(1,'problem','The starting point'),(2,'built','What I built'),(3,'detail','Under the hood'),(4,'lesson','What stayed with me')])+f'</div></section><a class="next-project" href="project-{PROJECTS[(i+1)%len(PROJECTS)]["slug"]}.html"><span class="eyebrow">NEXT ON THE SHELF</span><h2>{PROJECTS[(i+1)%len(PROJECTS)]["name"]} <span>↗</span></h2></a>'
    page('project-'+p['slug'],p['name'],p['intro'],body)

print('Built 11 static pages.')
